# .travis.yml
# Thanks! http://lua.space/general/ci-with-lua
language: python
sudo: false

env:
  - LUA="lua=5.3"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install busted
  - luarocks install luacheck
  - luarocks install luacov
  - luarocks install luacov-coveralls
  - luarocks install luasocket
  - luarocks install penlight

script:
  # - luacheck --std max+busted *.lua spec
  - busted --verbose --coverage .

after_success:
  - luacov-coveralls -e $TRAVIS_BUILD_DIR/lua_install